# Generated by Django 2.1 on 2018-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181010_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUsuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=35)),
                ('nome', models.CharField(max_length=85)),
                ('email', models.CharField(max_length=85, unique=True)),
                ('senha', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'home_usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
