# Generated by Django 2.1 on 2018-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181010_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=35, null=True)),
                ('nome', models.CharField(blank=True, max_length=85, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=85, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
