# Generated by Django 2.0 on 2018-10-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditos',
            fields=[
                ('credito_id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_creditos', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
    ]
