# Generated by Django 2.1 on 2018-10-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181013_1901'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditos',
            table=None,
        ),
    ]
