# Generated by Django 2.1 on 2018-10-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181015_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditos',
            table='creditos',
        ),
    ]
