# Generated by Django 2.1 on 2018-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'home_documento',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
