# Generated by Django 2.1 on 2018-10-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181017_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='valor_creditos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos_inseridos', models.CharField(max_length=50)),
                ('valorCreditos', models.CharField(max_length=35)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AuthUser')),
            ],
        ),
    ]
