# Generated by Django 2.1 on 2018-10-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_valor_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor_creditos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AuthUser'),
        ),
    ]
